services:
  server:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 127.0.0.1:5000:5000
    working_dir: /server
    volumes:
      - ./server:/server
    depends_on:
      oracledb:
        condition: service_healthy

  client:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - 127.0.0.1:3000:5173
    working_dir: /client
    volumes:
      - ./client:/client
  
  oracledb:
    image: container-registry.oracle.com/database/free
    ports:
      - 127.0.0.1:1521:1521
    volumes:
      - pomar-oracledb-data:/opt/oracle/oradata
      - ./server/database:/opt/oracle/scripts/startup
    healthcheck:
      test: ["CMD", "/opt/oracle/checkDBStatus.sh"]
      interval: 2s
    environment:
      - ORACLE_PWD=password

volumes:
  pomar-oracledb-data: