GRANT SELECT, INSERT, UPDATE, DELETE ON "SYS"."USERS" TO SYSTEM;
GRANT SELECT, INSERT, UPDATE, DELETE ON "SYS"."SPECIES" TO SYSTEM;
GRANT SELECT, INSERT, UPDATE, DELETE ON "SYS"."TREES" TO SYSTEM;
GRANT SELECT, INSERT, UPDATE, DELETE ON "SYS"."GROUPS" TO SYSTEM;
GRANT SELECT, INSERT, UPDATE, DELETE ON "SYS"."HARVESTS" TO SYSTEM;
GRANT SELECT, INSERT, UPDATE, DELETE ON "SYS"."TREES_GROUPS" TO SYSTEM;